---

- name: restart datadog-agent
  service:
    name: datadog-agent
    state: restarted
  when: datadog_enabled and not ansible_check_mode and not ansible_os_family == "Windows"

- name: restart datadog-agent-win
  win_service:
    name: datadogagent
    state: restarted
    force_dependent_services: true
  when: datadog_enabled and not ansible_check_mode and ansible_os_family == "Windows"
