apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: qotd
  labels:
    app: qotd
spec:
  selector:
    app: qotd
  replicas: 1
  template:
    metadata:
      labels:
        app: qotd
    spec:
      containers:
        - name: qotd
          image: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/qotd:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 10000
              protocol: TCP
  triggers:
  - type: ConfigChange 
  - imageChangeParams:
      automatic: true
      containerNames:
      - qotd
      from:
        kind: ImageStreamTag
        name: qotd:latest
    type: ImageChange