#apiVersion: cert-manager.io/v1alpha2
#kind: Issuer
#metadata:
#  name: letsencrypt-prod
#spec:
#  acme:
#    server: "https://acme-v02.api.letsencrypt.org/directory"
#    email: "codeaprendiz@gmail.com"
#    privateKeySecretRef:
#      name: letsencrypt-prod
#    solvers:
#      - http01:
#          ingress:
#            class: nginx

---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: le-crt
spec:
  secretName: tls-secret
  issuerRef:
    kind: Issuer
    name: letsencrypt
  commonName: devopsk8.com
  dnsNames:
    - devopsk8.com